return {
    { "catppuccin/nvim",              name = "catppuccin", priority = 1000 },
    { "miikanissi/modus-themes.nvim", name = "modus",      priority = 1000 },
    { "olivercederborg/poimandres.nvim", name = "poimandres",      priority = 1000 },
    { "morhetz/gruvbox", name = "gruvbox",      priority = 1000 },
    { "nlknguyen/papercolor-theme", name = "papercolor",      priority = 1000 },
    { "mofiqul/vscode.nvim", name = "vscode",      priority = 1000 },
    { "oxfist/night-owl.nvim", name = "nightowl",      priority = 1000 },
    { "ewilazarus/preto", name = "preto",      priority = 1000 },
    { "folke/tokyonight.nvim", name = "tokyonight",      priority = 1000 },
    { "rebelot/kanagawa.nvim", name = "kangawa",      priority = 1000 },
    { "kepano/flexoki-neovim", name = "flexoki",      priority = 1000 },
    { "bluz71/vim-nightfly-colors", name = "nightfly",      priority = 1000 },
    { "bluz71/vim-moonfly-colors", name = "moonfly",      priority = 1000 },
}
